language: objective-c
before_install:
  - brew update
install:
  - echo $PWD
  - ls $PWD
  - mkdir -p $(brew --repo)/Library/Taps/git-jiro
  - ln -s $PWD $(brew --repo)/Library/Taps/git-jiro/homebrew-jiro
  - brew tap --repair

script:
  - brew install gridcoin --HEAD --with-cli
